class EventsController < ApplicationController
  def index
    @events = [
      {
        title: "Tokyo Marathon 2025",
        city: "Tokyo",
        country: "Japan",
        date: "2025-03-02",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 100,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc",
        source_url: "https://www.marathon.tokyo/en/news/detail/news_003048.html"
      },
      {
        title: "Boston Marathon 2025",
        city: "Boston, MA",
        country: "USA",
        date: "2025-04-21",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 250,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://www.baa.org/races/boston-marathon"
      },
      {
        title: "TCS London Marathon 2025",
        city: "London",
        country: "United Kingdom",
        date: "2025-04-27",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 100,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
        source_url: "https://www.tcslondonmarathon.com/the-event/tcs-london-marathon-2025"
      },
      {
        title: "Schneider Electric Marathon de Paris 2025",
        city: "Paris",
        country: "France",
        date: "2025-04-13",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 120,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
        source_url: "https://www.backonmyfeet.org/event/2025-schneider-electric-paris-marathon/"
      },
      {
        title: "Harmonie Mutuelle Semi de Paris 2025",
        city: "Paris",
        country: "France",
        date: "2025-03-02",
        type: "Road Half Marathon",
        distance_km: 21.0975,
        elevation_gain_m: 80,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1511735111819-9a3f7709049c",
        source_url: "https://www.baa.org/races/boston-marathon"
      },
      {
        title: "Zurich Maratón de Sevilla 2025",
        city: "Seville",
        country: "Spain",
        date: "2025-02-23",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 60,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9",
        source_url: "https://www.maratondesevilla.es/"
      },
      {
        title: "Zurich Rock 'n' Roll Madrid Marathon 2025",
        city: "Madrid",
        country: "Spain",
        date: "2025-04-27",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 300,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1521550834646-8762f2fbaf44",
        source_url: "https://runrocknroll.com/madrid/"
      },
      {
        title: "NN Marathon Rotterdam 2025",
        city: "Rotterdam",
        country: "Netherlands",
        date: "2025-04-13",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 40,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1502567091907-2c9a3b3a0f82",
        source_url: "https://nnmarathonrotterdam.org/en/"
      },
      {
        title: "Run Rome The Marathon 2025",
        city: "Rome",
        country: "Italy",
        date: "2025-03-16",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 180,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1526481280698-8fcc13fd3b2e",
        source_url: "https://runromethemarathon.com/en/"
      },
      {
        title: "BMW Berlin Marathon 2025",
        city: "Berlin",
        country: "Germany",
        date: "2025-09-28",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 30,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1473950575850-d0b8f1dc2f37",
        source_url: "https://www.bz-berlin.de/berlin-2011/berliner-innenstadt/berlin-wahl-2025-und-bmw-berlin-marathon-kollision"
      },
      {
        title: "Bank of America Chicago Marathon 2025",
        city: "Chicago, IL",
        country: "USA",
        date: "2025-10-12",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 50,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1484249170766-998fa6efe3c0",
        source_url: "https://raceroster.com/events/2025/85525/2025-bank-of-america-chicago-marathon"
      },
      {
        title: "AJ Bell Great North Run 2025",
        city: "Newcastle",
        country: "United Kingdom",
        date: "2025-09-07",
        type: "Road Half Marathon",
        distance_km: 21.0975,
        elevation_gain_m: 120,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://www.greatrun.org/events/great-north-run/"
      },
      {
        title: "Sydney Marathon 2025",
        city: "Sydney",
        country: "Australia",
        date: "2025-09-14",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 200,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9",
        source_url: "https://www.sydneymarathon.com/2025-course-change"
      },
      {
        title: "Sanlam Cape Town Marathon 2025",
        city: "Cape Town",
        country: "South Africa",
        date: "2025-10-19",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 150,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://capetownmarathon.com/"
      },
      {
        title: "Standard Chartered Singapore Marathon 2025",
        city: "Singapore",
        country: "Singapore",
        date: "2025-12-06",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 120,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
        source_url: "https://singaporemarathon.com/"
      },
      {
        title: "Honolulu Marathon 2025",
        city: "Honolulu, HI",
        country: "USA",
        date: "2025-12-14",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 260,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1506086679524-493c64fdfaa6",
        source_url: "https://www.honolulumarathon.org/"
      },
      {
        title: "Valencia Marathon Trinidad Alfonso 2025",
        city: "València",
        country: "Spain",
        date: "2025-12-07",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 30,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1520962922320-2038eebab146",
        source_url: "https://www.pa-marathonvalencia.com/en/news/"
      },
      {
        title: "Tamarack Ottawa Marathon 2025",
        city: "Ottawa",
        country: "Canada",
        date: "2025-05-25",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 100,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
        source_url: "https://aims-worldrunning.org/race/1453"
      },
      {
        title: "Copenhagen Marathon 2025",
        city: "Copenhagen",
        country: "Denmark",
        date: "2025-05-11",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 80,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1566417713940-fa6de1e8f9c5",
        source_url: "https://results.copenhagenmarathon.dk/2025/?pid=event"
      },
      {
        title: "Dubai Marathon 2025",
        city: "Dubai",
        country: "United Arab Emirates",
        date: "2025-01-12",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 50,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
        source_url: "https://www.facebook.com/dubaimarathon/posts/pfbid0w1AaX1m5mX8s8c6C8QY3Z3JQp7yYg7eQ9b6Quj8g1jvR2f"
      },
      {
        title: "Tata Mumbai Marathon 2025",
        city: "Mumbai",
        country: "India",
        date: "2025-01-19",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 120,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
        source_url: "https://tatamumbaimarathon.procam.in/"
      },
      {
        title: "Gold Coast Marathon 2025 (Weekend)",
        city: "Gold Coast",
        country: "Australia",
        date: "2025-07-05",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 60,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1526521108-5b0c2c4c9c0b",
        source_url: "https://www.couriermail.com.au/sport/run/2025-gold-coast-marathon-course-changes-revealed/news-story/2d2b6b7b7c8bb"
      },
      {
        title: "Haspa Marathon Hamburg 2025",
        city: "Hamburg",
        country: "Germany",
        date: "2025-04-27",
        type: "Road Marathon",
        distance_km: 42.195,
        elevation_gain_m: 80,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1533681018184-68bd1d883546",
        source_url: "https://www.welt.de/256007154"
      },
      {
        title: "Sanlam Cape Town 10K 2025",
        city: "Cape Town",
        country: "South Africa",
        date: "2025-10-18",
        type: "Road 10K",
        distance_km: 10,
        elevation_gain_m: 80,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://capetownmarathon.com/"
      },
      {
        title: "Marathon international du Beaujolais",
        city: "Villefranche-sur-Saône",
        country: "France",
        date: "2025-11-22",
        type: "Marathon",
        distance_km: 42.195,
        elevation_gain_m: 150,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
        source_url: "https://fr.wikipedia.org/wiki/Marathon_international_du_Beaujolais"
      },
      {
        title: "Semi-marathon Marvejols-Mende",
        city: "Marvejols → Mende",
        country: "France",
        date: "2025-07-27",
        type: "Semi-marathon",
        distance_km: 19.0, # approximation *actual is longer than 21 but route specifics*
        elevation_gain_m: 400,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://fr.wikipedia.org/wiki/Semi-marathon_Marvejols-Mende"
      },
      {
        title: "Semi-marathon de Nice",
        city: "Nice",
        country: "France",
        date: "2025-04-20",
        type: "Semi-marathon",
        distance_km: 21.0975,
        elevation_gain_m: 50,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://fr.wikipedia.org/wiki/Semi-marathon_de_Nice"
      },
      {
        title: "Auray-Vannes",
        city: "Auray → Vannes",
        country: "France",
        date: "2025-09-14",
        type: "Semi-marathon",
        distance_km: 21.0975,
        elevation_gain_m: 100,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9",
        source_url: "https://fr.wikipedia.org/wiki/Auray-Vannes"
      },
      {
        title: "Toulouse Marathon Métropole",
        city: "Toulouse",
        country: "France",
        date: "2025-10-11",
        type: "Marathon",
        distance_km: 42.195,
        elevation_gain_m: 80,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
        source_url: "https://fr.wikipedia.org/wiki/Marathon_de_Toulouse_M%C3%A9tropole"
      },
      {
        title: "Semi-marathon du Chemin du Train Saugeais",
        city: "Gilley",
        country: "France",
        date: "2025-08-24",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 200,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Foulées Gouvillaises",
        city: "Gouville-sur-Mer",
        country: "France",
        date: "2025-08-23",
        type: "Semi-marathon",
        distance_km: 21.0,
        elevation_gain_m: 30,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Marathon des Oussaillès",
        city: "Saint-Girons",
        country: "France",
        date: "2025-08-24",
        type: "Marathon",
        distance_km: 42.195,
        elevation_gain_m: 300,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://www.ahotu.com/calendar/running/marathon/france"
      },
      {
        title: "Run in Séné Nature",
        city: "Séné",
        country: "France",
        date: "2025-08-24",
        type: "Trail / Semi-marathon",
        distance_km: 21.0,
        elevation_gain_m: 250,
        difficulty: "Advanced",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://www.ahotu.com/calendar/running/marathon/france"
      },
      {
        title: "Semi-marathon de Bolbec",
        city: "Bolbec",
        country: "France",
        date: "2025-09-05",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 60,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Les Foulées Giennoises",
        city: "Gien",
        country: "France",
        date: "2025-09-06",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 40,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Course des 2 Clochers",
        city: "Colleret",
        country: "France",
        date: "2025-08-24",
        type: "Semi-marathon",
        distance_km: 21.0,
        elevation_gain_m: 50,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://www.ahotu.com/calendar/running/semi-marathon/france"
      },
      {
        title: "Marathon international In Deauville",
        city: "Deauville",
        country: "France",
        date: "2025-11-15",
        type: "Marathon",
        distance_km: 42.195,
        elevation_gain_m: 70,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Semi-marathon de l'Armagnac",
        city: "Villeneuve-de-Marsan",
        country: "France",
        date: "2025-09-28",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 90,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://jogging-plus.com/calendrier/courses-5-10-15-km/france/"
      },
      {
        title: "Semi-marathon de Marcq-en-Barœul",
        city: "Marcq-en-Barœul",
        country: "France",
        date: "2025-09-20",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 70,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Semi-marathon Val de Fensch",
        city: "Uckange",
        country: "France",
        date: "2025-09-21",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 60,
        difficulty: "Intermediate",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "La Yussoise",
        city: "Yutz",
        country: "France",
        date: "2025-10-05",
        type: "Semi-marathon",
        distance_km: 21.1,
        elevation_gain_m: 50,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Les Foulées Montoises",
        city: "Mont-Bernanchon",
        country: "France",
        date: "2025-10-12",
        type: "Course 21 km",
        distance_km: 21.0,
        elevation_gain_m: 50,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
        source_url: "https://fr.milesrepublic.com/semi-marathon"
      },
      {
        title: "Corrida de Montech",
        city: "Montech",
        country: "France",
        date: "2025-08-22",
        type: "Course 10 km",
        distance_km: 10.0,
        elevation_gain_m: 20,
        difficulty: "Beginner",
        photo_url: "https://images.unsplash.com/photo-1520975922284-5f519b6b1a5a",
        source_url: "https://www.ahotu.com/calendar/running/france"
      }
    ]
  end
end
